### ISSUE TITLE
"use another dbdir" even with no dbdir!  What the hell?

### ISSUE THREAD

**Issue by Rudd-O** [goatpig/BitcoinArmory#139] opened 2016-11-13 09:51 UTC
Latest tag v0.95.1 dies with this:

```
   {
      //sanity check: try to open older SDBI version
      LMDBEnv::Transaction tx(dbEnv_[HEADERS].get(), LMDB::ReadOnly);
      BinaryData key;
      key.append(DB_PREFIX_DBINFO);
      auto valueRef = getValueNoCopy(HEADERS, key.getRef());

      if (valueRef.getSize() != 0)
      {
       	 //old style db, fail
         LOGERR << "DB version mismatch. Use another dbdir!";
         throw DbErrorMsg("DB version mismatch. Use another dbdir!");
      }
   }

   dbIsOpen_ = true;
}
```

I gotta ask: how can you ship broken software like that?  Broken software that handles millions of dollars for quite a few folks!

**Comment by Rudd-O** [comment] 2016-11-13 10:02
Moving the databases directory out of the way has no effect, because quitting Armory does not quit ArmoryDB, therefore it doesn't matter whether the frontend is restarted, the error keeps coming up.

This is rookie mistake B.S.

**Comment by Rudd-O** [comment] 2016-11-13 10:03
Serious rookie mistake.  How can quitting Armory not frigging end the ArmoryDB process, if it was autostarted by Armory?

**Comment by Rudd-O** [comment] 2016-11-13 10:04
Plus it's high time that this "oh, database version mismatch" B.S. stopped happening to begin with.  If the databases are the wrong version, and there's no data loss at stake, then move them the hell out of the way and rebuild them.  That's what should have been done from the start!

**Comment by hadzajlic** [comment] 2016-11-13 10:55
I had same problem . Solved by uninstalling armory 0.95.0 and delete ...\AppData\Roaming\Armory
Installed 0.95.1 
imported old wallet from backup .

**Comment by goatpig** [comment] 2016-11-13 13:21
1) What is broken about it? It detects version mismatch instead of failing silently. The version mismatch because the underlying data is different, out of necessity.

2) Most people are updating from 0.93. Others use terribly slow machines (1-2 cores, 2-4GB ram) with 0.94. It takes them a long time to build the DB, one way or another. There are too many unknowns and too little control over the users setup to just nuke a functional database by default over a version upgrade. 

I'd much rather let the user handle things manually for now, until I got some proper GUI to throw at them.

3) What you are complaining about is the UX, not the error handling detection. Basically, you want a dialog in the client to let you set your paths in a graphical way. I would love to have that in Armory, and one day I will add it.

4) There is way too much technical debt left in Armory to spend a release cycle on UX. The grand (and silent) majority of Armory users know how to juggle custom paths and swap DB folders from version to version. They also happen to participate in testing phases, where these inconveniences are detected. Incidentally, users expecting the plug and play experience the most also happen to completely skip testing phases.

5) I won't let the client just terminate the DB. It has to close it gracefully, which it doesn't do in the version mismatch case. Since this only happens during a messy upgrade, the case is isolated enough that the fix can wait for the next release. It is also part of a larger change that will move node RPC and auto management to the DB.

6) My current priority is SW. It forces the use of compressed public keys and the current Armory wallets do no allow for that. I will not change that code because it is robust, written in Python and age tested. This requires a lot of new code and the unit tests that go with them, plus a lot of SWIG magic to bridge the functionality over to the GUI. 

7) If you are unhappy with the UX, feel free to participate to testing phases, provide feedback and suggestions, or even submit PRs. No amateurish submissions like wiping the previous DB by default though.

8) Armory was maintained by ATI up until summer 2015. Their last open source version is 0.93.2. I took over open source development since March of this year. I do this on my own time, with no compensation . This was the state of Armory when I took over:

- no BIP32/44 implementation
- not even a path to SW support
- no support for compressed pub keys
- no support for HW signers
- no client server separation
- no multisig wallets
- unstable supernode
- DB was 1.5x blockchain size and took hours on end to build & scan
- An old signer and verifier code with no modularity or sane upgrade path
- No RBF detection nor ZC replacement mechanics

I hope to have most if not all of these issues addressed by the 1 year mark. You will notice there is no mention of UX in there. Days are only 24 hours long.

**Closed by goatpig** 2016-11-13 13:21 UTC

**Comment by Rudd-O** [comment] 2016-11-13 20:02
Explanation of how to reproduce it.

The detection is in ArmoryDB.  ArmoryDB starts when Armory starts.  Armory asks ArmoryDB, ArmoryDB replies "bad database version".  Armory closes.  ArmoryDB continues to run for some inexplicable reason.  I move the database files out of the way.  I start Armory.  Armory starts.  The old ArmoryDB replies to Armory again "bad database version" because it was still running when the files were moved, and it clearly has the old database files open.

Thus, nothing works, unless you are a UNIX expert and decide to ps ax, figure out Armory left junk processes running, kill them, and the restart Armory from scratch.

**Comment by Rudd-O** [comment] 2016-11-13 20:03
This bug should not be closed.  It's an actual bug.  It remains in the codebase.

Half the problem with the project is that these bugs do not get treated seriously.

**Comment by goatpig** [comment] 2016-11-13 20:23
This issue has already been layed out and plans made to address it in a place more suitable for the overarching level of the discussion. 

https://bitcointalk.org/index.php?topic=1670851.msg16787797#msg16787797

**Comment by Rudd-O** [comment] 2016-11-13 21:34
The bug tracker is to track the state of the issue.  If you close it now, there's no way people watching this bug can know at which particular commit the bug was actually fixed.

Do you really use Bitcointalk as a "bug tracker"?

*Facepalm*

**Comment by goatpig** [comment] 2016-11-13 22:02
The discussion started there, so I kept it there. Most of the user base follows the state of the project on that subforum, not here. It only makes sense to discuss these points where they are the most visible.

The github issue interface is more often than not dedicated to actually technical issues, not UX discussions. UX directly affects end users, why shouldn't the discussion be visible to them? I tolerate the  presence of UX tickets here and keep them open when the issue is too low on my priority list to deal with them within the current release cycle.

This discussion has far deviated from anything technical. It wasn't even technical to begin with. You dislike the UX and the DB fails to clean after itself under certain conditions. These issues have been taken in consideration and I've laid out a clear path on how to address them. You also were not the first one to point at this and the fix roadmap was decided before you even reported anything. 

If you were following the community discussions where they take place, you would have been in the loop much earlier, and prevented me from repeating myself. At any rate, redundancy cannot hurt, so at least there's that.

Your bug tracker point is moot:

- I do not use JIRA/FishEye/Crucible to manage the repo. You cannot in your right mind compare the github issue page to that kind feature. Anything short of that is basically a waste of effort.

- The code for the fix will most likely be delivered over several commits. Such is the nature of maintaining consistent UX accross the 3 major desktop OS. Again, the github issue page is too limited in features to convey that kind of a change set properly.

- Most bugs are detected during testing phases, and for this purpose, github is simply not as attractive as what has been the main source of information and discussion for Armory over the past 5+ years.

- I have forked Alan's repo. People that only look at the original github repo page aren't even aware that the project is still being maintained. All in all, github is not a consistent enough platform to track the project, and has never been regarded as such

- On that front, the previous team didn't bother addressing neither github issues not PRs. I'm doing this as a courtesy. You are too quick to discard the changes that have been undertaken since I took over. In the previous era, there wouldn't even be someone to read your rants, let alone respond.
