### ISSUE TITLE
Fails to build with clang: constructor cannot be redeclared

### ISSUE THREAD

**Issue by yurivict** [goatpig/BitcoinArmory#156] opened 2016-12-27 03:17 UTC
```
In file included from ./BDM_Server.h:23:
./DataObject.h:150:4: error: constructor cannot be redeclared
   IntType(size_t val) : val_(val)
   ^
```

0.95.1, clang FreeBSD clang version 3.8.0

**Comment by achow101** [comment] 2017-02-15 22:16
Duplicate of #137. Issue was fixed in #148. This can be closed now.

**Closed** 2017-02-15 22:16 UTC
